# Travis-CI build for belt
# see travis-ci.org for details

language: generic

os: linux
dist: trusty
sudo: required

before_install:
  - sudo apt-get install -y --no-install-recommends
      texlive-base texlive-latex-base texlive-latex-extra 
      texlive-latex-recommended texlive-generic-extra
      texlive-fonts-recommended texlive-generic-recommended
      texlive-fonts-extra texlive-lang-cyrillic 

script:
  - cd spec
  - pdflatex -interaction=nonstopmode -halt-on-error belt.tex
  - pdflatex -interaction=nonstopmode -halt-on-error belt.tex
  - cd ..

deploy:
  provider: releases
  api_key: 
    secure: OpHtvEMZ2v1fCjxQE1HzWn/llLkf6AGTFB4qUwDHCAunJXJSvwKOI8h1mbd2jXVFQH2RU/82nviRUHmhuW6oQ7siXbqzFnc+95HbIj3B5mdXWqrdcBp3RqT+Us/D1nB5vlr9lQaZW9XluTqVfy1fXniRej4BhSi4IBvnc7cE9APO+h02k0VfQ4tSZK1xGGD36MomaVvR05dDKJsrdzTLofdkWn7UUwTapT3S94FQmN1O+Y2OgbDMquSbyXnsdXUR+9ZJlXEtR6oyBdhJz3p7d07fMR0ohByoof5dbW8fxcuSS/0YonjluFpE1bfObLU1pUbdFIwaCZGBifqalIaqL3nJAAmxyDphjlWIH6xHryi+OR8nij9+LuXuk8jIoQj5qjww88yTdF6kHiDKMAVhdPkq17cUNnacq/NNGwBk/Mi4Ge2m9bA/i8fAads2NISYEWBwtT55bh9F6svKZSfJ3cBGXXIIDEC0wivWd0QTSnLCP98j5IZH6JCFLKg8eLgjaLB/8kTLpdfzeP/3lNAOQQG5DqDSk4TMIsRFtjSH47NVydsqdrp7wATMqkwFQLYz4MaiHX9KfFm7PtcTfglUOgXIh8GTDLFBLUsWJ1A61H6oYHNnvsxqJ/Yi2Qqq2A2+niq/W5xMQ9gesK/ycXhmsHPJ21Cfk+15qQ6n67dmj64=
  file: spec/belt.pdf
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true