name: build

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: belt.tex
          working_directory: spec/
          args: -jobname=belt -pdf -file-line-error -halt-on-error -interaction=nonstopmode
